package root

var expectedMutationEntities = map[string]string{
	"xp2p client disable":                      "edge-a",
	"xp2p client enable":                       "edge-a",
	"xp2p client forward add":                  "unicode-例.example:443",
	"xp2p client forward remove":               "62001",
	"xp2p client redirect add":                 "unicode-例.example",
	"xp2p client redirect disable":             "remove.example",
	"xp2p client redirect enable":              "remove.example",
	"xp2p client redirect remove":              "remove.example",
	"xp2p client reverse disable":              "reverse-a",
	"xp2p client reverse enable":               "reverse-a",
	"xp2p client subscription add":             "matrix",
	"xp2p client subscription refresh":         "matrix",
	"xp2p client subscription remove":          "matrix",
	"xp2p client update":                       "edge-a",
	"xp2p server forward add":                  "unicode-例.example:443",
	"xp2p server forward remove":               "62001",
	"xp2p server ha channel create":            "channel-1",
	"xp2p server ha channel disable":           "channel-1",
	"xp2p server ha channel finalize":          "channel-1",
	"xp2p server ha channel rebind":            "channel-1",
	"xp2p server ha channel rebind-endpoint":   "channel-1",
	"xp2p server ha group create":              "group-1",
	"xp2p server ha group remove":              "server ha group",
	"xp2p server ha group update":              "server ha group",
	"xp2p server ha member add":                "member-1",
	"xp2p server ha member remove":             "member-1",
	"xp2p server ha member reprioritize":       "member-1",
	"xp2p server ha peer add":                  "node-b",
	"xp2p server ha peer remove":               "node-b",
	"xp2p server ha peer self":                 "node-a",
	"xp2p server ha redirect add":              "unicode-例.example",
	"xp2p server ha redirect remove":           "matrix.example",
	"xp2p server ha sync":                      "server ha",
	"xp2p server identity detach":              "server identity",
	"xp2p server identity select":              "provider-例",
	"xp2p server identity sync":                "server identity",
	"xp2p server redirect access add-group":    "remove.example",
	"xp2p server redirect access add-user":     "remove.example",
	"xp2p server redirect access clear":        "remove.example",
	"xp2p server redirect access remove-group": "remove.example",
	"xp2p server redirect access remove-user":  "remove.example",
	"xp2p server redirect access set":          "remove.example",
	"xp2p server redirect add":                 "unicode-例.example",
	"xp2p server redirect disable":             "remove.example",
	"xp2p server redirect enable":              "remove.example",
	"xp2p server redirect remove":              "remove.example",
	"xp2p server reverse disable":              "reverse-a",
	"xp2p server reverse enable":               "reverse-a",
	"xp2p server user disable":                 "matrix-user",
	"xp2p server user enable":                  "matrix-user",
	"xp2p server user remove":                  "matrix-user",
	"xp2p server user update":                  "matrix-user",
}
