package root

import clioutput "github.com/NlightN22/xray-p2p/go/internal/cli/output"

type outputContract struct {
	class            string
	reason           string
	defaultOperation bool
}

func jsonContract() outputContract {
	return outputContract{class: clioutput.ClassJSON, defaultOperation: true}
}

func payloadContract() outputContract {
	return outputContract{class: clioutput.ClassJSON}
}

func exceptionContract(class, reason string) outputContract {
	return outputContract{class: class, reason: reason}
}

var outputContractInventory = map[string]outputContract{
	"xp2p client debug bundle":                 jsonContract(),
	"xp2p client deploy":                       payloadContract(),
	"xp2p client disable":                      jsonContract(),
	"xp2p client dns-forward add":              jsonContract(),
	"xp2p client dns-forward list":             payloadContract(),
	"xp2p client dns-forward remove":           jsonContract(),
	"xp2p client enable":                       jsonContract(),
	"xp2p client export":                       jsonContract(),
	"xp2p client forward add":                  jsonContract(),
	"xp2p client forward list":                 payloadContract(),
	"xp2p client forward remove":               jsonContract(),
	"xp2p client group list":                   payloadContract(),
	"xp2p client import":                       jsonContract(),
	"xp2p client install":                      jsonContract(),
	"xp2p client list":                         payloadContract(),
	"xp2p client mode":                         jsonContract(),
	"xp2p client obs":                          payloadContract(),
	"xp2p client redirect add":                 jsonContract(),
	"xp2p client redirect disable":             jsonContract(),
	"xp2p client redirect enable":              jsonContract(),
	"xp2p client redirect list":                payloadContract(),
	"xp2p client redirect remove":              jsonContract(),
	"xp2p client remove":                       jsonContract(),
	"xp2p client reverse disable":              jsonContract(),
	"xp2p client reverse enable":               jsonContract(),
	"xp2p client reverse list":                 payloadContract(),
	"xp2p client service restart":              jsonContract(),
	"xp2p client service start":                jsonContract(),
	"xp2p client service status":               payloadContract(),
	"xp2p client service stop":                 jsonContract(),
	"xp2p client state":                        payloadContract(),
	"xp2p client subscription add":             jsonContract(),
	"xp2p client subscription offers":          payloadContract(),
	"xp2p client subscription refresh":         jsonContract(),
	"xp2p client subscription remove":          jsonContract(),
	"xp2p client subscription status":          payloadContract(),
	"xp2p client update":                       jsonContract(),
	"xp2p heartbeat contract":                  payloadContract(),
	"xp2p nat-redirect add":                    jsonContract(),
	"xp2p nat-redirect list":                   payloadContract(),
	"xp2p nat-redirect remove":                 jsonContract(),
	"xp2p server cert set":                     jsonContract(),
	"xp2p server cert state":                   payloadContract(),
	"xp2p server debug bundle":                 jsonContract(),
	"xp2p server dns-forward add":              jsonContract(),
	"xp2p server dns-forward list":             payloadContract(),
	"xp2p server dns-forward remove":           jsonContract(),
	"xp2p server export":                       jsonContract(),
	"xp2p server forward add":                  jsonContract(),
	"xp2p server forward list":                 payloadContract(),
	"xp2p server forward remove":               jsonContract(),
	"xp2p server ha channel create":            jsonContract(),
	"xp2p server ha channel disable":           jsonContract(),
	"xp2p server ha channel finalize":          jsonContract(),
	"xp2p server ha channel inspect":           payloadContract(),
	"xp2p server ha channel list":              payloadContract(),
	"xp2p server ha channel rebind":            jsonContract(),
	"xp2p server ha channel rebind-endpoint":   jsonContract(),
	"xp2p server ha group create":              jsonContract(),
	"xp2p server ha group inspect":             payloadContract(),
	"xp2p server ha group remove":              jsonContract(),
	"xp2p server ha group update":              jsonContract(),
	"xp2p server ha member add":                jsonContract(),
	"xp2p server ha member list":               payloadContract(),
	"xp2p server ha member remove":             jsonContract(),
	"xp2p server ha member reprioritize":       jsonContract(),
	"xp2p server ha peer add":                  jsonContract(),
	"xp2p server ha peer list":                 payloadContract(),
	"xp2p server ha peer remove":               jsonContract(),
	"xp2p server ha peer self":                 jsonContract(),
	"xp2p server ha redirect add":              jsonContract(),
	"xp2p server ha redirect list":             payloadContract(),
	"xp2p server ha redirect remove":           jsonContract(),
	"xp2p server ha status":                    payloadContract(),
	"xp2p server ha sync":                      jsonContract(),
	"xp2p server identity detach":              jsonContract(),
	"xp2p server identity provision":           payloadContract(),
	"xp2p server identity select":              jsonContract(),
	"xp2p server identity status":              payloadContract(),
	"xp2p server identity sync":                jsonContract(),
	"xp2p server import":                       jsonContract(),
	"xp2p server install":                      payloadContract(),
	"xp2p server mode":                         jsonContract(),
	"xp2p server profile":                      jsonContract(),
	"xp2p server redirect access add-group":    jsonContract(),
	"xp2p server redirect access add-user":     jsonContract(),
	"xp2p server redirect access clear":        jsonContract(),
	"xp2p server redirect access remove-group": jsonContract(),
	"xp2p server redirect access remove-user":  jsonContract(),
	"xp2p server redirect access set":          jsonContract(),
	"xp2p server redirect add":                 jsonContract(),
	"xp2p server redirect disable":             jsonContract(),
	"xp2p server redirect enable":              jsonContract(),
	"xp2p server redirect list":                payloadContract(),
	"xp2p server redirect remove":              jsonContract(),
	"xp2p server remove":                       jsonContract(),
	"xp2p server reverse disable":              jsonContract(),
	"xp2p server reverse enable":               jsonContract(),
	"xp2p server reverse list":                 payloadContract(),
	"xp2p server service restart":              jsonContract(),
	"xp2p server service start":                jsonContract(),
	"xp2p server service status":               payloadContract(),
	"xp2p server service stop":                 jsonContract(),
	"xp2p server state":                        payloadContract(),
	"xp2p server user add":                     payloadContract(),
	"xp2p server user disable":                 jsonContract(),
	"xp2p server user enable":                  jsonContract(),
	"xp2p server user list":                    payloadContract(),
	"xp2p server user remove":                  jsonContract(),
	"xp2p server user rotate":                  payloadContract(),
	"xp2p server user update":                  jsonContract(),
	"xp2p completion": exceptionContract(clioutput.ClassGenerator,
		"the result is a shell completion script"),
	"xp2p docs command-map": exceptionContract(clioutput.ClassGenerator,
		"the result is a generated Markdown file"),
	"xp2p client render xray": exceptionContract(clioutput.ClassGenerator,
		"the result is an Xray JSON document"),
	"xp2p server render xray": exceptionContract(clioutput.ClassGenerator,
		"the result is an Xray JSON document"),
	"xp2p diag": exceptionContract(clioutput.ClassLifecycle,
		"the command runs a foreground diagnostics service"),
	"xp2p client run": exceptionContract(clioutput.ClassLifecycle,
		"the command runs Xray in the foreground"),
	"xp2p server run": exceptionContract(clioutput.ClassLifecycle,
		"the command runs Xray in the foreground"),
	"xp2p client service run": exceptionContract(clioutput.ClassLifecycle,
		"the command is an internal service entry point"),
	"xp2p server service run": exceptionContract(clioutput.ClassLifecycle,
		"the command is an internal service entry point"),
	"xp2p server deploy": exceptionContract(clioutput.ClassLifecycle,
		"the command runs a deployment listener"),
	"xp2p ping": exceptionContract(clioutput.ClassStreaming,
		"continuous ping output requires a future NDJSON contract"),
}

// platformSpecificOutputContracts are intentionally absent from command trees on
// unsupported hosts but remain explicit members of the public CLI inventory.
var platformSpecificOutputContracts = map[string]bool{
	"xp2p client dns-forward add":    true,
	"xp2p client dns-forward list":   true,
	"xp2p client dns-forward remove": true,
	"xp2p server dns-forward add":    true,
	"xp2p server dns-forward list":   true,
	"xp2p server dns-forward remove": true,
	"xp2p nat-redirect add":          true,
	"xp2p nat-redirect list":         true,
	"xp2p nat-redirect remove":       true,
}
