site_name: XP2P Tunnel provider
site_url: https://sitename.exmpl
nav:
  - Overview: index.md
  - Single Tunnel (A-B): 01-single-tunnel.md
  - Redirects Within A-B: 02-redirects.md
  - Chain (C2-B-A-C1): 03-chain.md
  - Advanced Variants: 04-advanced.md
  - Config Compilation: 08-config-compilation.md
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Roboto Mono
  palette: 
    - scheme:  slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: blue
      accent: deep purple

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: green
      accent: deep orange

  
