package main

import (
	"reflect"
	"strings"
	"time"
)

type schema map[string]any

type reflector struct {
	definitions map[string]any
	visiting    map[reflect.Type]bool
}

func newReflector() *reflector {
	return &reflector{definitions: map[string]any{}, visiting: map[reflect.Type]bool{}}
}

func (r *reflector) root(value any, id, title, description string) schema {
	result := r.inline(reflect.TypeOf(value))
	result["$schema"] = "http://json-schema.org/draft-04/schema#"
	result["$comment"] = "Code generated by make schema; DO NOT EDIT."
	result["id"] = id
	result["title"] = title
	result["description"] = description
	result["definitions"] = r.definitions
	return result
}

func (r *reflector) forType(t reflect.Type) schema {
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	if t == reflect.TypeOf(time.Time{}) {
		return schema{"type": "string", "format": "date-time"}
	}
	switch t.Kind() {
	case reflect.Struct:
		name := definitionName(t)
		if _, ok := r.definitions[name]; !ok && !r.visiting[t] {
			r.visiting[t] = true
			r.definitions[name] = r.inline(t)
			delete(r.visiting, t)
		}
		return schema{"$ref": "#/definitions/" + name}
	case reflect.Slice, reflect.Array:
		return schema{"type": "array", "items": r.forType(t.Elem())}
	case reflect.Map:
		return schema{"type": "object", "additionalProperties": r.forType(t.Elem())}
	case reflect.Bool:
		return schema{"type": "boolean"}
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return schema{"type": "integer"}
	case reflect.Float32, reflect.Float64:
		return schema{"type": "number"}
	case reflect.Interface:
		return schema{}
	default:
		return schema{"type": "string"}
	}
}

func (r *reflector) inline(t reflect.Type) schema {
	result := schema{"type": "object", "additionalProperties": false, "properties": map[string]any{}}
	properties := result["properties"].(map[string]any)
	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		if field.PkgPath != "" {
			continue
		}
		if field.Anonymous {
			embedded := r.inline(field.Type)
			for key, value := range embedded["properties"].(map[string]any) {
				properties[key] = value
			}
			continue
		}
		name := fieldName(field)
		if name != "" && name != "-" {
			properties[name] = r.forType(field.Type)
		}
	}
	return result
}

func fieldName(field reflect.StructField) string {
	for _, tagName := range []string{"toml", "koanf", "json"} {
		if tag, ok := field.Tag.Lookup(tagName); ok {
			return strings.Split(tag, ",")[0]
		}
	}
	return toSnake(field.Name)
}

func definitionName(t reflect.Type) string {
	pkg := t.PkgPath()
	if index := strings.LastIndex(pkg, "/"); index >= 0 {
		pkg = pkg[index+1:]
	}
	return pkg + "_" + toSnake(t.Name())
}

func toSnake(value string) string {
	var out strings.Builder
	for i, ch := range value {
		if i > 0 && ch >= 'A' && ch <= 'Z' {
			out.WriteByte('_')
		}
		out.WriteRune(ch)
	}
	return strings.ToLower(out.String())
}
