//go:build linux

package firewall

import (
	"encoding/json"
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

func renderSnippet(entries []Entry) string {
	if len(entries) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("# Autogenerated by xp2p nat-redirect.\n")
	b.WriteString("table inet xray_transparent {\n")
	b.WriteString("    chain xray_transparent_prerouting {\n")
	b.WriteString("        type nat hook prerouting priority -95; policy accept;\n")
	for _, e := range entries {
		b.WriteString(fmt.Sprintf("        meta l4proto tcp tcp dport != %d ip daddr %s counter redirect to :%d\n", e.Port, e.Subnet, e.Port))
	}
	b.WriteString("    }\n")
	b.WriteString("    chain xray_transparent_output {\n")
	b.WriteString("        type nat hook output priority -95; policy accept;\n")
	for _, e := range entries {
		b.WriteString(fmt.Sprintf("        meta l4proto tcp tcp dport != %d ip daddr %s counter redirect to :%d\n", e.Port, e.Subnet, e.Port))
	}
	b.WriteString("    }\n")
	b.WriteString("    chain xray_transparent_output_allow {\n")
	b.WriteString("        type filter hook output priority 0; policy accept;\n")
	seen := make(map[int]bool)
	for _, e := range entries {
		if !seen[e.Port] {
			b.WriteString(fmt.Sprintf("        tcp dport %d counter accept\n", e.Port))
			seen[e.Port] = true
		}
	}
	b.WriteString("    }\n")
	b.WriteString("}\n")
	return b.String()
}

func renderIPTables(entries []Entry) []string {
	commands := []string{
		"iptables -t nat -N XRAY_TRANSPARENT || iptables -t nat -F XRAY_TRANSPARENT",
		"iptables -t filter -N XRAY_TRANSPARENT_OUT || iptables -t filter -F XRAY_TRANSPARENT_OUT",
		"iptables -t nat -C PREROUTING -j XRAY_TRANSPARENT || iptables -t nat -I PREROUTING 1 -j XRAY_TRANSPARENT",
		"iptables -t nat -C OUTPUT -j XRAY_TRANSPARENT || iptables -t nat -I OUTPUT 1 -j XRAY_TRANSPARENT",
		"iptables -t filter -C OUTPUT -j XRAY_TRANSPARENT_OUT || iptables -t filter -I OUTPUT 1 -j XRAY_TRANSPARENT_OUT",
		"iptables -t nat -F XRAY_TRANSPARENT",
		"iptables -t filter -F XRAY_TRANSPARENT_OUT",
	}
	for _, e := range entries {
		commands = append(commands,
			fmt.Sprintf("iptables -t nat -A XRAY_TRANSPARENT -p tcp -d %s ! --dport %d -j REDIRECT --to-ports %d", e.Subnet, e.Port, e.Port),
			fmt.Sprintf("iptables -t filter -A XRAY_TRANSPARENT_OUT -p tcp --dport %d -j ACCEPT", e.Port),
		)
	}
	if len(entries) == 0 {
		commands = append(commands,
			"iptables -t nat -D PREROUTING -j XRAY_TRANSPARENT || true",
			"iptables -t nat -D OUTPUT -j XRAY_TRANSPARENT || true",
			"iptables -t filter -D OUTPUT -j XRAY_TRANSPARENT_OUT || true",
			"iptables -t nat -X XRAY_TRANSPARENT || true",
			"iptables -t filter -X XRAY_TRANSPARENT_OUT || true",
		)
	}
	return commands
}

func applyIPTables(plan Plan) error {
	for _, cmd := range plan.IPTables {
		parts := strings.Fields(cmd)
		if len(parts) == 0 {
			continue
		}
		if err := exec.Command(parts[0], parts[1:]...).Run(); err != nil {
			return fmt.Errorf("nat redirect: iptables apply: %w", err)
		}
	}
	if err := persistIPTables(); err != nil {
		return fmt.Errorf("nat redirect: persist iptables: %w", err)
	}
	return nil
}

func selectBackend() string {
	if commandExists("fw4") || commandExists("nft") {
		return "nft"
	}
	return "iptables"
}

func commandExists(name string) bool {
	_, err := exec.LookPath(name)
	return err == nil
}

func persistIPTables() error {
	if !commandExists("iptables-save") {
		return fmt.Errorf("iptables-save not available")
	}
	out, err := exec.Command("iptables-save").Output()
	if err != nil {
		return fmt.Errorf("iptables-save: %w", err)
	}
	target := "/etc/iptables/rules.v4"
	if _, err := os.Stat(filepath.Dir(target)); err != nil {
		target = "/etc/iptables/iptables.rules"
	}
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return fmt.Errorf("create iptables dir: %w", err)
	}
	if err := os.WriteFile(target, out, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", target, err)
	}
	return nil
}

func validateCIDR(value string) error {
	if _, _, err := net.ParseCIDR(value); err != nil {
		return fmt.Errorf("nat redirect: invalid subnet %s: %w", value, err)
	}
	return nil
}

func DetectDokodemoPorts(path string) ([]int, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("nat redirect: read %s: %w", path, err)
	}
	type inbound struct {
		Protocol string `json:"protocol"`
		Port     int    `json:"port"`
	}
	doc := struct {
		Inbounds []inbound `json:"inbounds"`
	}{}
	if err := json.Unmarshal(data, &doc); err != nil {
		return nil, fmt.Errorf("nat redirect: parse %s: %w", path, err)
	}
	var ports []int
	for _, inb := range doc.Inbounds {
		if strings.TrimSpace(inb.Protocol) == "dokodemo-door" && inb.Port > 0 {
			ports = append(ports, inb.Port)
		}
	}
	return ports, nil
}
