//go:build linux

package firewall

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

type Entry struct {
	Subnet string
	Port   int
}

type Plan struct {
	Snippet     string
	SnippetPath string
	EntryPath   string
	IPTables    []string
	Backend     string
	RemoveAll   bool
	Entry       *Entry
}

type Manager struct {
	snippetPath string
	entryDir    string
}

func NewManager(snippetPath, entryDir string) Manager {
	return Manager{
		snippetPath: strings.TrimSpace(snippetPath),
		entryDir:    strings.TrimSpace(entryDir),
	}
}

func (m Manager) List() ([]Entry, error) {
	paths, err := filepath.Glob(filepath.Join(m.entryDir, "*.entry"))
	if err != nil {
		return nil, fmt.Errorf("nat redirect: list entries: %w", err)
	}
	sort.Strings(paths)
	var entries []Entry
	for _, p := range paths {
		e, err := readEntry(p)
		if err == nil && e.Subnet != "" && e.Port > 0 {
			entries = append(entries, e)
		}
	}
	return entries, nil
}

func (m Manager) PlanAdd(subnet string, port int) (Plan, error) {
	if err := validateCIDR(subnet); err != nil {
		return Plan{}, err
	}
	if port <= 0 || port > 65535 {
		return Plan{}, fmt.Errorf("nat redirect: port must be between 1 and 65535")
	}
	entries, err := m.List()
	if err != nil {
		return Plan{}, err
	}
	updated := upsertEntry(entries, Entry{Subnet: subnet, Port: port})
	snippet := renderSnippet(updated)
	entryPath := entryPathForSubnet(m.entryDir, subnet)
	return Plan{
		Snippet:     snippet,
		SnippetPath: m.snippetPath,
		EntryPath:   entryPath,
		IPTables:    renderIPTables(updated),
		Backend:     selectBackend(),
		Entry:       &Entry{Subnet: subnet, Port: port},
	}, nil
}

func (m Manager) PlanRemove(subnet string, all bool) (Plan, error) {
	entries, err := m.List()
	if err != nil {
		return Plan{}, err
	}
	var updated []Entry
	var entryPath string
	switch {
	case all:
		updated = nil
		entryPath = ""
	case subnet != "":
		if err := validateCIDR(subnet); err != nil {
			return Plan{}, err
		}
		entryPath = entryPathForSubnet(m.entryDir, subnet)
		for _, e := range entries {
			if e.Subnet != subnet {
				updated = append(updated, e)
			}
		}
	default:
		return Plan{}, fmt.Errorf("nat redirect: subnet or --all required")
	}
	snippet := renderSnippet(updated)
	return Plan{
		Snippet:     snippet,
		SnippetPath: m.snippetPath,
		EntryPath:   entryPath,
		IPTables:    renderIPTables(updated),
		Backend:     selectBackend(),
		RemoveAll:   all,
	}, nil
}

func renderSnippet(entries []Entry) string {
	if len(entries) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("# Autogenerated by xp2p nat-redirect.\n")
	b.WriteString("table inet xray_transparent {\n")
	b.WriteString("    chain xray_transparent_prerouting {\n")
	b.WriteString("        type nat hook prerouting priority -95; policy accept;\n")
	for _, e := range entries {
		b.WriteString(fmt.Sprintf("        meta l4proto tcp tcp dport != %d ip daddr %s counter redirect to :%d\n", e.Port, e.Subnet, e.Port))
	}
	b.WriteString("    }\n")
	b.WriteString("    chain xray_transparent_output {\n")
	b.WriteString("        type nat hook output priority -95; policy accept;\n")
	for _, e := range entries {
		b.WriteString(fmt.Sprintf("        meta l4proto tcp tcp dport != %d ip daddr %s counter redirect to :%d\n", e.Port, e.Subnet, e.Port))
	}
	b.WriteString("    }\n")
	b.WriteString("    chain xray_transparent_output_allow {\n")
	b.WriteString("        type filter hook output priority 0; policy accept;\n")
	seen := make(map[int]bool)
	for _, e := range entries {
		if !seen[e.Port] {
			b.WriteString(fmt.Sprintf("        tcp dport %d counter accept\n", e.Port))
			seen[e.Port] = true
		}
	}
	b.WriteString("    }\n")
	b.WriteString("}\n")
	return b.String()
}

func renderIPTables(entries []Entry) []string {
	commands := []string{
		"iptables -t nat -N XRAY_TRANSPARENT || iptables -t nat -F XRAY_TRANSPARENT",
		"iptables -t filter -N XRAY_TRANSPARENT_OUT || iptables -t filter -F XRAY_TRANSPARENT_OUT",
		"iptables -t nat -C PREROUTING -j XRAY_TRANSPARENT || iptables -t nat -I PREROUTING 1 -j XRAY_TRANSPARENT",
		"iptables -t nat -C OUTPUT -j XRAY_TRANSPARENT || iptables -t nat -I OUTPUT 1 -j XRAY_TRANSPARENT",
		"iptables -t filter -C OUTPUT -j XRAY_TRANSPARENT_OUT || iptables -t filter -I OUTPUT 1 -j XRAY_TRANSPARENT_OUT",
		"iptables -t nat -F XRAY_TRANSPARENT",
		"iptables -t filter -F XRAY_TRANSPARENT_OUT",
	}
	for _, e := range entries {
		commands = append(commands,
			fmt.Sprintf("iptables -t nat -A XRAY_TRANSPARENT -p tcp -d %s ! --dport %d -j REDIRECT --to-ports %d", e.Subnet, e.Port, e.Port),
			fmt.Sprintf("iptables -t filter -A XRAY_TRANSPARENT_OUT -p tcp --dport %d -j ACCEPT", e.Port),
		)
	}
	if len(entries) == 0 {
		commands = append(commands,
			"iptables -t nat -D PREROUTING -j XRAY_TRANSPARENT || true",
			"iptables -t nat -D OUTPUT -j XRAY_TRANSPARENT || true",
			"iptables -t filter -D OUTPUT -j XRAY_TRANSPARENT_OUT || true",
			"iptables -t nat -X XRAY_TRANSPARENT || true",
			"iptables -t filter -X XRAY_TRANSPARENT_OUT || true",
		)
	}
	return commands
}

func applyIPTables(plan Plan) error {
	for _, cmd := range plan.IPTables {
		parts := strings.Fields(cmd)
		if len(parts) == 0 {
			continue
		}
		if err := exec.Command(parts[0], parts[1:]...).Run(); err != nil {
			return fmt.Errorf("nat redirect: iptables apply: %w", err)
		}
	}
	return nil
}

func selectBackend() string {
	if commandExists("fw4") || commandExists("nft") {
		return "nft"
	}
	return "iptables"
}

func commandExists(name string) bool {
	_, err := exec.LookPath(name)
	return err == nil
}

func validateCIDR(value string) error {
	if _, _, err := net.ParseCIDR(value); err != nil {
		return fmt.Errorf("nat redirect: invalid subnet %s: %w", value, err)
	}
	return nil
}

func DetectDokodemoPorts(path string) ([]int, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("nat redirect: read %s: %w", path, err)
	}
	type inbound struct {
		Protocol string `json:"protocol"`
		Port     int    `json:"port"`
	}
	doc := struct {
		Inbounds []inbound `json:"inbounds"`
	}{}
	if err := json.Unmarshal(data, &doc); err != nil {
		return nil, fmt.Errorf("nat redirect: parse %s: %w", path, err)
	}
	var ports []int
	for _, inb := range doc.Inbounds {
		if strings.TrimSpace(inb.Protocol) == "dokodemo-door" && inb.Port > 0 {
			ports = append(ports, inb.Port)
		}
	}
	return ports, nil
}
