<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ui-xp2p</AssemblyName>
    <RootNamespace>Xp2pUi</RootNamespace>
    <ApplicationIcon>..\..\assets\xp2p.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="..\..\assets\xp2p.ico">
      <Link>assets\xp2p.ico</Link>
    </Resource>
    <Resource Include="..\..\assets\Base.png">
      <Link>assets\Base.png</Link>
    </Resource>
    <Resource Include="..\..\assets\Disabled.png">
      <Link>assets\Disabled.png</Link>
    </Resource>
    <Resource Include="..\..\assets\Enabled.png">
      <Link>assets\Enabled.png</Link>
    </Resource>
    <Resource Include="..\..\assets\Enabling.png">
      <Link>assets\Enabling.png</Link>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\assets\Base.png">
      <LogicalName>assets/Base.png</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\assets\Disabled.png">
      <LogicalName>assets/Disabled.png</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\assets\Enabled.png">
      <LogicalName>assets/Enabled.png</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\assets\Enabling.png">
      <LogicalName>assets/Enabling.png</LogicalName>
    </EmbeddedResource>
    <Content Include="..\..\assets\Base.png">
      <Link>assets\Base.png</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\assets\Disabled.png">
      <Link>assets\Disabled.png</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\assets\Enabled.png">
      <Link>assets\Enabled.png</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\assets\Enabling.png">
      <Link>assets\Enabling.png</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.0" />
    <PackageReference Include="ModernWpfUI" Version="0.9.7-preview.2" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Xp2pUi.Tests" />
  </ItemGroup>
</Project>
