from __future__ import annotations

from tests.host.cross.helpers_common import assert_link_install_dir, extract_marker
from tests.host.cross.helpers_linux import (
    assert_linux_server_install_dir,
    detect_linux_ipv4_non_nat,
    linux_runner,
    read_optional_linux_log,
    reset_linux_logs,
    start_linux_client_deploy,
    start_linux_server_deploy,
    wait_for_client_link_linux,
    wait_for_error_phrase_linux,
    wait_for_log_phrase_linux,
    wait_for_log_value_linux,
)
from tests.host.cross.helpers_windows import (
    WindowsProcInfo,
    assert_windows_server_install_dir,
    assert_windows_tcp_reachable,
    cleanup_windows_client_install,
    cleanup_windows_server_install,
    detect_windows_ipv4,
    ensure_windows_ready,
    read_combined_windows_logs,
    read_optional_windows_text,
    reset_windows_logs,
    start_windows_client_deploy,
    start_windows_server_deploy,
    stop_windows_process,
    wait_for_client_link_windows,
    wait_for_error_phrase_windows,
    wait_for_log_phrase_windows,
    wait_for_log_value_windows,
    wait_for_windows_ssh,
    windows_runner,
)

__all__ = [
    "WindowsProcInfo",
    "assert_link_install_dir",
    "assert_linux_server_install_dir",
    "assert_windows_server_install_dir",
    "assert_windows_tcp_reachable",
    "cleanup_windows_client_install",
    "cleanup_windows_server_install",
    "detect_linux_ipv4_non_nat",
    "detect_windows_ipv4",
    "ensure_windows_ready",
    "extract_marker",
    "linux_runner",
    "read_combined_windows_logs",
    "read_optional_linux_log",
    "read_optional_windows_text",
    "reset_linux_logs",
    "reset_windows_logs",
    "start_linux_client_deploy",
    "start_linux_server_deploy",
    "start_windows_client_deploy",
    "start_windows_server_deploy",
    "stop_windows_process",
    "wait_for_client_link_linux",
    "wait_for_client_link_windows",
    "wait_for_error_phrase_linux",
    "wait_for_error_phrase_windows",
    "wait_for_log_phrase_linux",
    "wait_for_log_phrase_windows",
    "wait_for_log_value_linux",
    "wait_for_log_value_windows",
    "wait_for_windows_ssh",
    "windows_runner",
]
