Vagrant.configure("2") do |config|
  config.vm.box = "openwrt-gw"
  ALPINE_CLIENT_BOX         = "generic/alpine318".freeze
  ALPINE_CLIENT_BOX_VERSION = "4.3.12".freeze
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.allow_fstab_modification = false
  config.ssh.insert_key = false
  config.ssh.private_key_path = File.expand_path("~/.vagrant.d/insecure_private_keys/vagrant.key.rsa")

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus = 2
  end

  load File.expand_path("routers.rb", __dir__)
  define_routers(config)

  load File.expand_path("clients.rb", __dir__)
  define_clients(config)

end
