//go:build linux

package client

import (
	"fmt"
	"net"
	"os"
	"strings"

	"github.com/NlightN22/xray-p2p/go/internal/logging"
)

const resolvConfPath = "/etc/resolv.conf"

func applyDNSOverrides(servers []string) (*fullTunnelDNSBackup, error) {
	trimmed := filterDNSValues(servers)
	if len(servers) == 0 {
		return nil, nil
	}
	if len(trimmed) == 0 {
		return nil, fmt.Errorf("xp2p: dns servers list is empty")
	}
	data, err := os.ReadFile(resolvConfPath)
	if err != nil {
		return nil, fmt.Errorf("xp2p: read resolv.conf: %w", err)
	}
	backup := &fullTunnelDNSBackup{
		ResolvConf: string(data),
		ResolvPath: resolvConfPath,
	}
	content := buildResolvConf(string(data), trimmed)
	if err := os.WriteFile(resolvConfPath, []byte(content), 0o644); err != nil {
		return nil, fmt.Errorf("xp2p: write resolv.conf: %w", err)
	}
	logging.Info("xp2p: full-tunnel DNS servers applied", "path", resolvConfPath)
	return backup, nil
}

func restoreDNSOverrides(backup *fullTunnelDNSBackup) error {
	if backup == nil || backup.ResolvConf == "" {
		return nil
	}
	path := resolvConfPath
	if strings.TrimSpace(backup.ResolvPath) != "" {
		path = strings.TrimSpace(backup.ResolvPath)
	}
	if err := os.WriteFile(path, []byte(backup.ResolvConf), 0o644); err != nil {
		return fmt.Errorf("xp2p: restore resolv.conf: %w", err)
	}
	logging.Info("xp2p: full-tunnel DNS servers restored", "path", path)
	return nil
}

func buildResolvConf(existing string, servers []string) string {
	var lines []string
	lines = append(lines, "# generated by xp2p full-tunnel")
	for _, server := range servers {
		trimmed := strings.TrimSpace(server)
		if trimmed == "" {
			continue
		}
		lines = append(lines, "nameserver "+trimmed)
	}
	for _, line := range strings.Split(existing, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "nameserver") {
			continue
		}
		lines = append(lines, line)
	}
	return strings.Join(lines, "\n") + "\n"
}

func filterDNSValues(servers []string) []string {
	var out []string
	for _, server := range servers {
		trimmed := strings.TrimSpace(server)
		if trimmed == "" {
			continue
		}
		if net.ParseIP(trimmed) == nil {
			continue
		}
		out = append(out, trimmed)
	}
	return out
}
