# frozen_string_literal: true

BOX_NAME     = "gusztavvargadr/windows-10".freeze
BOX_VERSION  = "2202.0.2505".freeze
MACHINE_NAME = "xp2p-win10".freeze
HOST_SYNCED_ROOT = File.expand_path("../../..", __dir__)
PROVISION_SCRIPT = File.expand_path("scripts/provision.ps1", __dir__)

Vagrant.configure("2") do |config|
  config.vm.box = BOX_NAME
  config.vm.box_version = BOX_VERSION
  config.vm.guest = :windows
  config.vm.boot_timeout = 900
  config.vm.communicator = "winrm"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder HOST_SYNCED_ROOT, "C:/xp2p", type: "virtualbox"

  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"
  config.winrm.transport = :plaintext
  config.winrm.timeout = 600
  config.winrm.retry_limit = 30

  config.vm.network "forwarded_port",
                    guest: 5985,
                    host: 55985,
                    protocol: "tcp",
                    id: "winrm",
                    auto_correct: true

  config.vm.network "forwarded_port",
                    guest: 22,
                    host: 55922,
                    protocol: "tcp",
                    id: "ssh",
                    auto_correct: true

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.name = MACHINE_NAME
    vb.memory = 4096
    vb.cpus = 2
    vb.gui = false
  end

  config.vm.provision "shell",
                      path: PROVISION_SCRIPT,
                      privileged: true
end
