# frozen_string_literal: true

BOX_NAME              = "gusztavvargadr/windows-10".freeze
BOX_VERSION           = "2202.0.2505".freeze
SERVER_ID             = "win10-server".freeze
CLIENT_ID             = "win10-client".freeze
SERVER_VM_NAME        = "xp2p-win10-server".freeze
CLIENT_VM_NAME        = "xp2p-win10-client".freeze
SERVER_PRIVATE_IP     = "10.0.10.1".freeze
CLIENT_PRIVATE_IP     = "10.0.10.10".freeze
HOST_SYNCED_ROOT      = File.expand_path("../../..", __dir__)
PROVISION_SCRIPT      = File.expand_path("scripts/provision.ps1", __dir__)
DEFAULT_WINRM_PORT    = 5985
SERVER_WINRM_HOSTPORT = 55985
CLIENT_WINRM_HOSTPORT = 55986

def define_xp2p_machine(config, machine_id:, vb_name:, role:, private_ip:, winrm_host_port:)
  config.vm.define machine_id do |machine|
    machine.vm.box = BOX_NAME
    machine.vm.box_version = BOX_VERSION
    machine.vm.guest = :windows
    machine.vm.boot_timeout = 900
    machine.vm.communicator = "winrm"

    machine.vm.synced_folder ".", "/vagrant", disabled: true
    machine.vm.synced_folder HOST_SYNCED_ROOT, "C:/xp2p", type: "virtualbox"

    machine.winrm.username = "vagrant"
    machine.winrm.password = "vagrant"
    machine.winrm.transport = :plaintext
    machine.winrm.basic_auth_only = true
    machine.winrm.timeout = 600
    machine.winrm.retry_limit = 30

    machine.vm.network "forwarded_port",
                       guest: DEFAULT_WINRM_PORT,
                       host: winrm_host_port,
                       protocol: "tcp",
                       id: "#{machine_id}-winrm",
                       auto_correct: true

    machine.vm.network "private_network",
                       ip: private_ip

    machine.vm.provider "virtualbox" do |vb|
      vb.name = vb_name
      vb.memory = 4096
      vb.cpus = 2
      vb.gui = false
    end

    machine.vm.provision "shell",
                         path: PROVISION_SCRIPT,
                         privileged: true,
                         env: { "XP2P_ROLE" => role }
  end
end

Vagrant.configure("2") do |config|
  define_xp2p_machine(
    config,
    machine_id: SERVER_ID,
    vb_name: SERVER_VM_NAME,
    role: "server",
    private_ip: SERVER_PRIVATE_IP,
    winrm_host_port: SERVER_WINRM_HOSTPORT
  )

  define_xp2p_machine(
    config,
    machine_id: CLIENT_ID,
    vb_name: CLIENT_VM_NAME,
    role: "client",
    private_ip: CLIENT_PRIVATE_IP,
    winrm_host_port: CLIENT_WINRM_HOSTPORT
  )
end
