# frozen_string_literal: true

BOX_NAME              = "jborean93/WindowsServer2019".freeze
BOX_VERSION           = "1.2.0".freeze
SERVER_ID             = "win2019-a".freeze
CLIENT_ID             = "win2019-b".freeze
SERVER_VM_NAME        = "win2019-a".freeze
CLIENT_VM_NAME        = "win2019-b".freeze
SERVER_PRIVATE_IP     = "10.62.10.41".freeze
CLIENT_PRIVATE_IP     = "10.62.10.42".freeze
HOST_SYNCED_ROOT      = File.expand_path("../../..", __dir__)
SHARED_SCRIPTS_ROOT   = File.expand_path("../scripts/win", __dir__)
OPENSSH_SCRIPT        = File.expand_path("openssh.ps1", SHARED_SCRIPTS_ROOT)
NETWORK_SETUP_SCRIPT  = File.expand_path("network_setup.ps1", SHARED_SCRIPTS_ROOT)
PROVISION_SCRIPT      = File.expand_path("builder_provision.ps1", SHARED_SCRIPTS_ROOT)
DEFAULT_WINRM_PORT    = 5986
SERVER_WINRM_HOSTPORT = 56885
CLIENT_WINRM_HOSTPORT = 56886
SSH_GUEST_PORT        = 2222
SERVER_SSH_HOSTPORT   = 52112
CLIENT_SSH_HOSTPORT   = 52113

def define_xp2p_machine(config, machine_id:, vb_name:, role:, private_ip:, winrm_host_port:, ssh_host_port:)
  config.vm.define machine_id do |machine|
    machine.vm.box = BOX_NAME
    machine.vm.box_version = BOX_VERSION
    machine.vm.guest = :windows
    machine.vm.boot_timeout = 800
    machine.vm.communicator = "winrm"
    machine.vm.hostname = vb_name

    machine.vm.synced_folder ".", "/vagrant", disabled: true
    machine.vm.synced_folder HOST_SYNCED_ROOT, "C:/xp2p", type: "virtualbox"

    machine.winrm.username = "vagrant"
    machine.winrm.password = "vagrant"
    machine.winrm.transport = :ssl
    machine.winrm.basic_auth_only = true
    machine.winrm.ssl_peer_verification = false
    machine.winrm.host = "127.0.0.1"
    machine.winrm.port = winrm_host_port
    machine.winrm.timeout = 400
    machine.winrm.retry_delay = 60
    machine.winrm.retry_limit = 10

    machine.ssh.username = "vagrant"
    machine.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key"]
    machine.ssh.host = private_ip
    machine.ssh.port = SSH_GUEST_PORT
    machine.ssh.insert_key = false

    machine.vm.network "forwarded_port",
                       guest: DEFAULT_WINRM_PORT,
                       host: winrm_host_port,
                       protocol: "tcp",
                       id: "#{machine_id}-winrm",
                       auto_correct: true

    machine.vm.network "forwarded_port",
                       guest: SSH_GUEST_PORT,
                       host: ssh_host_port,
                       protocol: "tcp",
                       id: "#{machine_id}-ssh",
                       auto_correct: true

    machine.vm.network "private_network",
                       ip: private_ip

    machine.vm.provider "virtualbox" do |vb|
      vb.name = vb_name
      vb.memory = 6144
      vb.cpus = 4
      vb.linked_clone = false
      vb.gui = false
    end

    shared_env = {
      "XP2P_ROLE" => role,
      "XP2P_MACHINE_ID" => machine_id,
      "XP2P_SYNC_ROOT" => "C:/xp2p"
    }

    machine.vm.provision "shell",
                         name: "openssh",
                         path: OPENSSH_SCRIPT,
                         privileged: true,
                         env: shared_env

    machine.vm.provision "shell",
                         name: "network-setup",
                         path: NETWORK_SETUP_SCRIPT,
                         privileged: true,
                         args: [private_ip],
                         env: shared_env

    machine.vm.provision "shell",
                         name: "msi-deps",
                         path: PROVISION_SCRIPT,
                         privileged: true,
                         env: shared_env
  end
end

Vagrant.configure("2") do |config|
  define_xp2p_machine(
    config,
    machine_id: SERVER_ID,
    vb_name: SERVER_VM_NAME,
    role: "server",
    private_ip: SERVER_PRIVATE_IP,
    winrm_host_port: SERVER_WINRM_HOSTPORT,
    ssh_host_port: SERVER_SSH_HOSTPORT
  )

  define_xp2p_machine(
    config,
    machine_id: CLIENT_ID,
    vb_name: CLIENT_VM_NAME,
    role: "client",
    private_ip: CLIENT_PRIVATE_IP,
    winrm_host_port: CLIENT_WINRM_HOSTPORT,
    ssh_host_port: CLIENT_SSH_HOSTPORT
  )
end
