<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>xp2p-ui</AssemblyName>
    <RootNamespace>Xp2pUi</RootNamespace>
    <ApplicationIcon>assets\xp2p.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="assets\xp2p.ico" />
    <Resource Include="assets\Base.png" />
    <Resource Include="assets\Disabled.png" />
    <Resource Include="assets\Enabled.png" />
    <Resource Include="assets\Enabling.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="assets\Base.png" />
    <EmbeddedResource Include="assets\Disabled.png" />
    <EmbeddedResource Include="assets\Enabled.png" />
    <EmbeddedResource Include="assets\Enabling.png" />
    <Content Include="assets\Base.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="assets\Disabled.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="assets\Enabled.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="assets\Enabling.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.0" />
    <PackageReference Include="ModernWpfUI" Version="0.9.7-preview.2" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Xp2pUi.Tests" />
  </ItemGroup>
</Project>
