project_root = File.expand_path('../../..', __dir__)

BOX_PATH = File.expand_path('../boxes/openwrt-24.10.2.box', __dir__)
BOX_NAME = 'openwrt-24.10.2'.freeze
BUILD_OUTPUT = File.join(project_root, 'build', 'ipk')
HOST_NETMASK = ENV.fetch('OPENWRT_HOST_NETMASK', '255.255.255.0')
HOST_INTERFACE = ENV.fetch('OPENWRT_HOST_INTERFACE', 'eth1')

ROUTER_PROVISION = File.expand_path('../openwrt-scripts/router-provision.sh', __dir__)
MACHINES = [
  { id: 'openwrt-a', hostname: 'openwrt-a', vb_name: 'openwrt-a', forwarded_port: 2221, private_ip: '10.62.20.11', tunnel_ip: '10.63.30.11', lan_suffix: 1 },
  { id: 'openwrt-b', hostname: 'openwrt-b', vb_name: 'openwrt-b', forwarded_port: 2222, private_ip: '10.62.20.12', tunnel_ip: '10.63.30.12', lan_suffix: 2 },
  { id: 'openwrt-c', hostname: 'openwrt-c', vb_name: 'openwrt-c', forwarded_port: 2223, private_ip: '10.62.20.13', tunnel_ip: '10.63.30.13', lan_suffix: 3 },
].freeze

Vagrant.configure('2') do |config|
  MACHINES.each do |machine|
    config.vm.define machine[:id] do |vm|
      vm.vm.box = BOX_NAME
      vm.vm.box_url = BOX_PATH
      vm.vm.hostname = machine[:hostname]

      vm.ssh.insert_key = false
      vm.vm.boot_timeout = 200
      vm.vm.synced_folder '.', '/vagrant', disabled: true

      vm.vm.network 'forwarded_port', guest: 22, host: machine[:forwarded_port], auto_correct: true
      vm.vm.network 'private_network', ip: machine[:private_ip], auto_config: false
      vm.vm.network 'private_network', auto_config: false, virtualbox__intnet: 'xp2p_tunnel'

      vm.vm.provider 'virtualbox' do |vb|
        vb.name = machine[:vb_name]
        vb.gui = false
        vb.memory = 1024
        vb.cpus = 2
      end

      vm.vm.provision 'file', source: BUILD_OUTPUT, destination: '/tmp/build-openwrt'
      vm.vm.provision 'shell', path: ROUTER_PROVISION, args: [machine[:tunnel_ip], machine[:lan_suffix]], privileged: false
    end
  end
end
